addSbtPlugin("org.typelevel"     % "sbt-typelevel" % "0.4.6")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"  % "2.4.6")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"  % "0.9.34")
addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "5.6.0")
addSbtPlugin("com.timushev.sbt"  % "sbt-rewarn"    % "0.1.3")
